[package]
name = "axum-mcp-macros"
version = "0.1.0"
edition = "2024"
description = "Procedural macros for axum-mcp (#[mcp_tool])"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
